// DBI Cache definition

// User-defined header files
#include "mem/cache/dbi_cache.hh"

// C++ related header files
#include <cassert> // For assert()

// gem5 specific header files
#include "base/logging.hh"
#include "base/trace.hh"
#include "base/types.hh"
#include "debug/Cache.hh"
#include "mem/cache/cache_blk.hh"
#include "mem/cache/mshr.hh"

// gem5 autogenerated file
#include "params/DBICache.hh"
